name = "hedwig"
main = "workers/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "TSCN_SESSION"
class_name = "TscnSession"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TscnSession"]

[browser]
binding = "BROWSER"